"""essage=init

Revision ID: d95af555b076
Revises: 
Create Date: 2023-07-13 19:01:36.571244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95af555b076'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('captcha',
    sa.Column('captcha_text', sa.Text(), nullable=False),
    sa.Column('captcha_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('captcha_text')
    )
    op.create_table('channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('channel_id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('channels')
    op.drop_table('captcha')
    op.drop_table('admins')
    # ### end Alembic commands ###
